// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="Why Choose Vinanza"
          title="Staffing Excellence Driven by Quality"
          description="We specialize in matching talented, trained individuals with high-impact events. Our commitment to professionalism ensures every guest is treated with exceptional service."
          items={[
            { icon: "CheckCircle", title: "Verified Talent", description: "Rigorous vetting process to ensure professionalism." },
            { icon: "Shield", title: "Fully Insured", description: "Complete coverage for peace of mind." },
            { icon: "Zap", title: "Rapid Deployment", description: "Last-minute scaling capabilities." },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/people-working-their-office_23-2149196434.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
