// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get Started"
          text="Ready to staff your next event with professional excellence?"
          primaryButton={{ text: "Contact Us", href: "mailto:hello@vinanza.com" }}
          secondaryButton={{ text: "Book Now", href: "#" }}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
