// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Q&A"
          title="Common Questions"
          description="Everything you need to know about our staffing services."
          categories={[
            { name: "General", items: [{ question: "How far in advance should we book?", answer: "We recommend 2 weeks, but can handle urgent requests." }, { question: "Are your staff insured?", answer: "Yes, all staff are fully covered." }] },
            { name: "Services", items: [{ question: "What types of events do you staff?", answer: "Corporate, private, wedding, and large conferences." }] },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
