// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBento from '@/components/sections/features/FeaturesBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBento
          tag="Our Expertise"
          title="Comprehensive Event Solutions"
          description="Tailored staffing solutions for diverse event categories."
          features={[
            {
              title: "Corporate Events",          description: "Professional support for meetings and conferences.",          bentoComponent: "info-card-marquee",          infoCards: [
                { icon: "Briefcase", label: "Events", value: "500+" },
                { icon: "Users", label: "Staff", value: "200+" },
              ],
            },
            {
              title: "Hospitality Crew",          description: "Top tier waitstaff and service teams.",          bentoComponent: "tilted-stack-cards",          stackCards: [
                { icon: "Users", title: "Server", subtitle: "Staff", detail: "Expert catering service." },
                { icon: "Clock", title: "Bar", subtitle: "Tender", detail: "Professional mixing." },
                { icon: "Star", title: "Host", subtitle: "Service", detail: "Welcoming experience." },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
