// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroTiltedCards from '@/components/sections/hero/HeroTiltedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroTiltedCards
          tag="Premier Staffing Solutions"
          title="Elevate Your Events with Professional Staff"
          description="Vinanza provides top-tier hospitality and event personnel tailored for corporate, private, and large-scale gatherings."
          primaryButton={{
            text: "Get a Quote",        href: "#contact"}}
          secondaryButton={{
            text: "Our Services",        href: "#features"}}
          items={[
            { imageSrc: "http://img.b2bpic.net/free-photo/people-taking-part-business-event_23-2149333663.jpg" },
            { imageSrc: "http://img.b2bpic.net/free-photo/lovely-family-enjoying-new-year-party_23-2149173314.jpg" },
            { imageSrc: "http://img.b2bpic.net/free-photo/partners-sitting-table-working-cafe_1157-28472.jpg" },
            { imageSrc: "http://img.b2bpic.net/free-photo/friends-having-fun-drinking-champagne-outdoors_197531-5879.jpg" },
            { imageSrc: "http://img.b2bpic.net/free-photo/smiling-female-staff-standing_107420-85117.jpg" },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
