/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { motion } from "motion/react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

type AboutMediaOverlayProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const MemoriesInline = () => {
  return (
    <section aria-label="About section" className="py-20">
      <div className="flex flex-col items-center gap-12 py-8 md:py-12 mx-auto w-content-width">
        <div className="flex items-center justify-center px-5 mx-auto w-full max-w-3xl">
          <div className="flex flex-col items-center gap-2 text-center">
            <motion.span
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-15%" }}
              transition={{ duration: 0.4, ease: "easeOut" }}
              className="mb-1 px-3 py-1 text-sm card rounded"
            >
              {"Memories"}
            </motion.span>

            <TextAnimation
              text={"Our Core Team"}
              variant={"slide-up"}
              gradientText={true}
              tag="h2"
              className="text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-balance text-primary-cta-text"
            />

            <TextAnimation
              text={"A look back at some of the best moments with our dedicated staff who make every event special."}
              variant={"slide-up"}
              gradientText={false}
              tag="p"
              className="text-lg md:text-xl leading-snug text-balance text-primary-cta-text"
            />

            {(undefined || undefined) && (
              <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
                {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
                {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default function MemoriesSection() {
  return (
    <div data-webild-section="memories" data-section="memories" id="memories">
      <MemoriesInline />
    </div>
  );
}
