// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Our Impact"
          title="Proven Results in Event Staffing"
          description="Delivering excellence at every touchpoint."
          metrics={[
            { value: "98%", title: "Client Satisfaction", features: ["On-time delivery", "Professionalism"] },
            { value: "250+", title: "Events Staffed", features: ["Corporate", "Weddings"] },
            { value: "1500+", title: "Service Hours", features: ["Hospitality", "Operations"] },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
