// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamOverlayCards from '@/components/sections/team/TeamOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamOverlayCards
          tag="Leadership"
          title="Meet Our Management Team"
          description="Dedicated professionals committed to event success."
          members={[
            { name: "Elena Vance", role: "Director", imageSrc: "http://img.b2bpic.net/free-photo/businessman-dress-code-holding-black-jacket-his-arm_114579-15947.jpg" },
            { name: "Marcus Thorne", role: "Ops Lead", imageSrc: "http://img.b2bpic.net/free-photo/young-trans-man-working-as-waiter_23-2149409815.jpg" },
            { name: "Sarah Jenkins", role: "Recruiting", imageSrc: "http://img.b2bpic.net/free-photo/male-jeweler-working-shop_23-2150914246.jpg" },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
