// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeOverlayCards
          tag="Trust"
          title="What Our Clients Say"
          description="Real feedback from satisfied event organizers."
          testimonials={[
            { name: "Jessica Lee", role: "Event Planner", company: "Global Gala", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/colleagues-having-fun-business-event_23-2149370487.jpg" },
            { name: "David Smith", role: "COO", company: "CorpConnect", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/portrait-mature-businessman-with-crossed-arms-standing-restaurant_23-2147955310.jpg" },
            { name: "Amelia Ross", role: "Manager", company: "Luxury Events", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/male-guest-waiting-check_482257-79729.jpg" },
            { name: "Brian K.", role: "Director", company: "Elite Hospitality", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/handsome-tattooed-man-summer-terrace-city-cafe-is-drinking-wine-street-cafe_1321-20.jpg" },
            { name: "Sophie P.", role: "Founder", company: "Vogue Galas", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/front-view-portrait-beautiful-woman_23-2148317338.jpg" },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
